### ISSUE TITLE
How to get text with range?

### ISSUE THREAD

**Issue by chenfanfang** [ChimeHQ/SwiftTreeSitter#11]
help me please.
can you tell me how to get text with range?
thanks!

**Comment by chenfanfang** [comment]
How to get textString with node range

**Comment by mattmassicotte** [comment]
SwiftTreeSitter is text system-independent. This means that it does not have a way to get the text contents directly. You must connect it to the system you are using. If you have, for example, a Node value, you can access its `range` within your text. But, it is up to you to use that range to get the content.

I hope this is helpful!

**Comment by chenfanfang** [comment]
I see, thank you
