### ISSUE TITLE
Investigate issues with emoji 

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/SwiftTreeSitter#12]
@kaunteya reported that there are issues with handling emoji. I think these are all typically multi-point characters in UTF16, which is on the rare side. But, it would mean there are encoding/decoding issues and need to be investigated.

**Comment by mattmassicotte** [comment]
The reported problem is tripping the assertion within `func data(at byteOffset: Int, limit: Int, using encoding: String.Encoding, chunkSize: Int) -> Data?`

**Comment by mattmassicotte** [comment]
I've added a test, but I'm now suspecting this bug is entirely within https://github.com/ChimeHQ/Neon. I found an issue with `TextViewHighlighter`'s handling of multi-point characters.

**Comment by mattmassicotte** [comment]
@kaunteya are you using `TextViewHighlighter` in the places you have reproduced this problem?

**Comment by mattmassicotte** [comment]
Can you try out the main branch of Neon and see if it addresses the issue?

**Comment by kaunteya** [comment]
Hey Matt.
I updated Neon Package in my code and it seems the issue has not been fixed yet.
Getting this error

```
SwiftTreeSitter/String+Data.swift:19: Fatal error: location is greater than end
```

I am using this commit `2e947934a75108a06fa42db84f69101d08a46f5c` from the main branch

**Comment by mattmassicotte** [comment]
Ok well I’ll keep at it! Have not been able to reproduce the issue with the neon example project yet…

Do you happen to know of any steps I can do it make it happen there?

**Comment by kaunteya** [comment]
I was able to reproduce it while inserting an emoji in a String.
Attaching a screen recording for reference

https://user-images.githubusercontent.com/2352321/211006519-17bf175a-a301-4efc-91e2-37c4113720a2.mov

**Comment by mattmassicotte** [comment]
Hmmm. I cannot cause this to happen. What OS are you running? Are you using a x86_64 machine?

**Comment by kaunteya** [comment]
Yes

**Comment by mattmassicotte** [comment]
Ok, so I tried to reproduce this on the only Intel machine I could get access to, which was running 12.6. I was unable to cause the crash. However, since you seem to be able to do it, maybe we can work together to try to debug?

**Comment by mattmassicotte** [comment]
Ok, so the first thing to do is to check out the latest version of this repo and run the unit tests. I added a bunch to try to exercise this area. If any of those cause problems, it will help us focus.

**Comment by kaunteya** [comment]
The Unit tests run fine. No issues there. I am on this commit `d015661` 
Did you add any new tests? I am not able to see any new tests added recently.

**Comment by mattmassicotte** [comment]
Yeah there is a new parsing test called `testParseEmojiInEdit` I’d like to try. And if it passes, I think the next step is to figure out how to take whatever is going wrong in Neon and capture that as a test here.

**Comment by kaunteya** [comment]
I can confirm, `testParseEmojiInEdit()` is passing successfully in my mac

**Comment by mattmassicotte** [comment]
Huh, ok well that's good to know, but it surprised me. This test was supposed to exactly emulate what you did.

So, I looked more closely at your screen recording, and it looks like you first insert an emoji without issue. But, then you insert a second, and that's what crashes. First, is that right? And if so, we can try expanding the test to cover that.

**Comment by kaunteya** [comment]
Yes. That's right. It works fine for the first emoji

**Comment by mattmassicotte** [comment]
Hmm ok, well that's a clue. I'll make another test that does two edits.

**Comment by mattmassicotte** [comment]
While I do that, it would also be helpful to understand the state in that function at the time of the first edit and the second. Could you set a breakpoint on that assertion, and provide the values of:

`byteOffset`, `limit`, `encoding`, `chunkSize`, `location` and `end` every time it gets hit? I know this is a pain...

**Comment by mattmassicotte** [comment]
(And that test is now ready I think)

**Comment by kaunteya** [comment]
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/2352321/214491018-7fc9387a-1fd7-4a05-882a-9d11e83cf718.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/2352321/214491135-841625d2-16f2-4e41-bf88-3cfff9f16e53.png">

**Comment by mattmassicotte** [comment]
Ok, this is useful. The limit is `40`, and that is **incorrect**. That's quite surprising. Are you certain you are using the latest main branch?

**Comment by kaunteya** [comment]
Oh my bad. Got confused while working between Neon and SwiftTreeSitter.
On the latest pull in Neon repo, the above crash does not happen

**Comment by mattmassicotte** [comment]
Hooray, we figured it out!! Thanks for reporting this and all your help along the way.
