### ISSUE TITLE
`QueryCursor.highlights()` highlights same token multiple times

### ISSUE THREAD

**Issue by augustwester** [ChimeHQ/SwiftTreeSitter#16]
I'm using SwiftTreeSitter for syntax highlighting in my app. However, I find that highlights obtained using

```swift
let cursor = query.execute(node: tree.rootNode!)
var attrString = AttributedString(stringLiteral: code)
        
for highlight in cursor.highlights() {
    print(highlight.name) // for debugging (see below)
    print(highlight.range)
    let range = Range(highlight.range, in: attrString)!
    let attr = HighlightTheme.attributesFor(name: highlight.name)
    attrString[range].mergeAttributes(attr)
```

gives different results from using the same parser and highlighter in the tree-sitter CLI. I'm not sure if this is because I'm using SwiftTreeSitter the wrong way or because there's a bug. Here's an example:

Given a string containing the following very simple C code

```rust
// my main function
int main() {
    printf("Hello World\n");
    return 0;
}
```

the code above outputs:

```
comment
{0, 19}
type
{20, 3}
function <---
{24, 4}
constant <---
{24, 4}
variable <---
{24, 4}
...
```

i.e. the token "main" is marked as both a function, a constant, and a variable. This messes with my highlighting, since "main" will be marked as a variable, not a function. I see in [the docs](https://swiftpackageindex.com/chimehq/swifttreesitter/0.7.1/documentation/swifttreesitter/querycursor/highlights()) that in the `highlights()` function "[r]esults are sorted such that less-specific matches come before more-specific." In that case, I could keep track of whether I've seen a specific range before and ignore any subsequent matches for that range. However, for other languages, I find that the order is different. Here is another example in Rust:

```rust
// my main function
fn main() {
    println!("Hello World");
}
```

which yields:

```
comment
{0, 19}
keyword
{20, 2}
constant <---
{23, 4}
constructor <---
{23, 4}
function <---
{23, 4}
...
```

I was curious to see whether this was due to a problem with the different `highlight.scm` files I'm using, so I ran `tree-sitter highlight test.c` and `tree-sitter highlight test.rs` (i.e. the same snippets I've shown above) with the same parser and `highlight.scm` files and found that the code is highlighted properly.

Is this expected behavior? If so, how do I deal with it?

**Comment by mattmassicotte** [comment]
This is an interesting report!

So, tree-sitter's "highlighting system" actually isn't part of tree-sitter itself, but is more of an ad-hoc specification. The implementation is left entirely up to the client, of which the tree-sitter CLI is one. SwiftTreeSitter is another.

It looks like, in this case, the patterns defined in these highlights.scm are ambiguous. I have found that many are, leading to multiple matches. Which is exactly why I had to specify this behavior.

If I'm understanding right, the ordering is different for Rust and C. How does the CLI prioritize ambiguous matches? I'm not opposed to making changes here, but I do not fully understand what the change should be yet.

**Comment by augustwester** [comment]
I just tried using `ResolvingQueryCursor` instead, and it does make a difference!

In the Rust example, each token is only matched once (great!), while the C example now gives:

```
comment
{0, 19}
type
{20, 3}
function <---
{24, 4}
variable <---
{24, 4}
...
```

i.e. it no longer matches on "constant" and the matches are still given in the correct order. Will have to test it some more, but if this is any indication, I should be able to solve the problem by doing:

```swift
let cursor = query.execute(node: tree.rootNode!)
let resolvingCursor = ResolvingQueryCursor(cursor: cursor)
var attrString = AttributedString(stringLiteral: component.content)
      
for highlight in resolvingCursor.highlights() {
    let range = Range(highlight.range, in: attrString)!
    let attr = HighlightTheme.attributesFor(name: highlight.name)
    attrString[range].mergeAttributes(attr, mergePolicy: .keepCurrent)
}
```

Will post an update when I've tested it more thoroughly.

**Comment by augustwester** [comment]
Unfortunately, I just found a counterexample. Using the parser and `highlights.scm` in tree-sitter-java, the `ResolvingQueryCursor.highlights()` for the following Java code

```java
public class Main {
    // my main method
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
```

gives

```
keyword
{0, 6}
keyword
{7, 5}
type <---
{13, 4}
variable <---
{13, 4}
comment
{24, 17}
keyword
{46, 6}
keyword
{53, 6}
type.builtin
{60, 4}
variable <---
{65, 4}
function.method <---
{65, 4}
...
```

In the first example, `Main` matches as "type" before "variable", which is fine if best matches come first. However, in the last example, `main` first matches as "variable" (wrong) and then "function.method" (correct).

I'm still new to tree-sitter, so I just realized (correct me if I'm wrong) that what is meant by

> Results are sorted such that less-specific matches come before more-specific.

is that "variable" (less specific) will come before "function.method" (more specific) but not necessarily before, say, "function". In other words, if a token has multiple and equally specific matches, the order is not guaranteed and I won't be able to highlight the code correctly.

**Comment by mattmassicotte** [comment]
The thing we really want to understand is if the matches being returned are consistent with what is inside of the "highlights.scm" file. Multiple matches are 100% allowed (and common) by queries. I really do want to stress that "right" vs "wrong" is not the correct way to think about this issue. What matters is does this do what the query tells the system to do, ambiguities *included*.

Making your life more complex, I have found many highlights.scm files to be poorly-maintained and/or just plain wrong. I frequently tweak them myself, and try to submit patches when appropriate. I'm actually in the middle of doing this for Swift now. But I have done this for a number of other parsers.

As for the ordering, it is always deterministic. If two matches have the same number of components, like "variable" and "function", then they are ordered by how they appear within the query definition file. I'm unsure if there is any alternative that could work better, but I'm open to suggestions.

As an aside, I've begun work on a higher-level library within SwiftTreeSitter, called TreeSitterDocument. It is specifically built to help people use tree-sitter successfully without needing to understand the system fully. Just wanted to make you aware.
