### ISSUE TITLE
Help configuring norg syntax

### ISSUE THREAD

**Issue by figitaki** [ChimeHQ/SwiftTreeSitter#17]
I've been trying for a few days to get [tree-sitter-norg](https://github.com/nvim-neorg/tree-sitter-norg) to work with this library, however I cannot get a build artifact to work.

**Comment by figitaki** [comment]
Fixed.

**Comment by mattmassicotte** [comment]
Glad you got it working. Parsers can be quite difficult to set up. If you have any interest in SPM-ifying that one, I'd be happy to help. It looks quite standard, so should be straightforward.

**Comment by figitaki** [comment]
Thanks for checking in! Managed to get SPM setup. The issue I was running into was adding support for C++14 extension functionality. Opened an issue on the swift repo and got an answer there. Hopefully the changes will land soon and I can open a PR to update your README to indicate support! https://github.com/nvim-neorg/tree-sitter-norg/pull/52

**Comment by mattmassicotte** [comment]
oh wow, I wouldn't have known how to do that either. So many parsers have their own little quirks unfortunately. Very glad you figured it out, and super-cool of you to get that PR opened!
