### ISSUE TITLE
Weird crash happening while accessing properties on Node

### ISSUE THREAD

**Issue by kaunteya** [ChimeHQ/SwiftTreeSitter#18]
I am facing a strange issue where the Node if accessed in the function is not crashing but if it is accessed in the called function then it crashes.

```swift
class ViewModel: NSObject {
    let textStorage = NSTextStorage()
    let treeSitterClient: TreeSitterClient
    let query: Query

    func node(at location: Int) async throws -> Node? {
        let currentTree = try await treeSitterClient.currentTree()
        var root: Node = currentTree.rootNode!.firstChild!
        print(root.parent) // <- Does not crash here
        return root
    }

    func getPath(range: NSRange) {
        Task { @MainActor in
            let node = try! await node(at: range.location)!
            print(node.parent) // <- But crashes here
        }
    }
}

```

The crash is reproducible even when I access other properties like `nextSibling`, `prevSibling` in `getPath()` function.
The crash however DOESNT happen when I access `namedChildCount` & `childCount` in `getPath()` function.
Does it have to be something related to Node being a `struct`?

I have removed other irrelevant code. If required I can create a standalone minimum reproducible

**Comment by mattmassicotte** [comment]
Hmm. There's a lot of async behavior here, and TreeSitterClient (which is in the [Neon](https://github.com/ChimeHQ/Neon) repo, not this one) wasn't really designed to provide this level of access to the underlying tree.

I'd be happy to look at an example. Let's move the discussion over to the repo where this code lives. I think what we will find is ultimately you need both exclusive and synchronous access to the tree and TreeSitterClient does not provide that. Perhaps we can look into alternatives though.

**Comment by kaunteya** [comment]
Created a [new issue](https://github.com/ChimeHQ/Neon/issues/22) with an example project on Neon's repo.
