### ISSUE TITLE
export Node.internalNode id field

### ISSUE THREAD

**Issue by lijunsong** [ChimeHQ/SwiftTreeSitter#26]
TSNode is defined as

```
typedef struct {
  uint32_t context[4];
  const void *id;
  const TSTree *tree;
} TSNode;
```

Any reason to not export the `id` field in `Node` struct?

For example, the rust implementation of markdown parser uses the `id` field to id nodes (markdown parser is a split parser, two parsers work together to parse markdown).

**Comment by mattmassicotte** [comment]
Hmm, interesting idea! Can you help me understand what the rust runtime  implementation is doing with the `id`? Is it using to test for node equality?

I'm definitely not opposed to this in principle, I'd just like to make sure I understand exactly how it would be used.

**Comment by lijunsong** [comment]
yes.

The markdown parser (the tree sitter markdown) requires 2 phases parsing: the first phase parses high level blocks (title, paragraphs, lists), and the second phase parses inline markdown (say inside a paragraph there is a `**s**` strong emphasis).

The rust implementation sets the parser to markdown language, parses once to get a block tree, and then walks through the block tree to get nodes marked `inline`. For those inline nodes, the parser switches to markdown_inline language, parses one more time for each node to get a tree from the inline node.

The end result is that we get a block tree that represents high level blocks, and a mapping from node.id (nodes are in the block tree) to inline tree. When you walk through block tree, you see a node that's an inline type, you can easily jump to the inline tree using the node's id.

**Comment by lijunsong** [comment]
Currently the Node is equitable

```
extension Node: Equatable {
    public static func == (lhs: Node, rhs: Node) -> Bool {
        return ts_node_eq(lhs.internalNode, rhs.internalNode)
    }
}
```

But only Equitable is not sufficient to implement such an idea. Either we need node.id or we need to make `Node` Hashable.

**Comment by mattmassicotte** [comment]
Ok I see!

What do you think about the example in the readme here: https://github.com/ChimeHQ/SwiftTreeSitter#highlighting? This uses the tree-sitter injection system to solve this problem in a general way. It works with many other languages, and does not require custom code or internal knowledge of how a particular parser works.

But I also think it could be a great idea to implement `Hashable`.

**Comment by lijunsong** [comment]
Seems general enough for highlighting. I'd like precise control to my parser though.

**Comment by mattmassicotte** [comment]
Yes, the layering system will work for an arbitrary number of nestings with any tree-sitter query. And the language parser loading can be fully asynchronous. Many existing parsers support these injections, this markdown parser included. However, to automatically union query results across all nestings, the queries have to be well-known. There aren't too many of those, but highlights is a really common one.

But, if you want to build something custom for this parser I'd like to make that possible. Do you think the best way is via Hashable or just exposing that raw pointer?

**Comment by lijunsong** [comment]
I read more tree-sitter code. The `id` has been used internally for recording subtree, so it's kinda weird to export it.

I am testing making the `Node` hashable. Drafting https://github.com/ChimeHQ/SwiftTreeSitter/compare/main...lijunsong:SwiftTreeSitter:main (I'll add unittest later when I confirm this works for me).

**Comment by lijunsong** [comment]
OK here is my conclusion:
1. Making Node Hashable leads confusing results: because Equitable calls `tree_node_eq`, which takes into account both `id` and `tree` field: when re-parsing after edit, a node `id` doesn't change, but `tree` does change, so it makes things wrong in different places if we only consider `id` in hash value.
2. Exporting `id` directly makes everything correct in my case (and the rust implementation of MarkdownParser), but I am not sure as a library what others want this `id` for, so I have no suggestion on the actual implementation. I simply return that UInt back

     ```
    public var id: UInt {
        return UInt(bitPattern: internalNode.id)
    }
    ```

What your take on this?

**Comment by mattmassicotte** [comment]
Thanks so much for doing this investigation!

Yeah, I was worried about how `Hashable` would turn out. I'm totally fine with exposing the `id` directly. I think your implemenation is good!
